spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: default-server
          uri: lb://DEFAULT-SERVER
          predicates:
            - Path=/v1/default/**
          filters:
            - RewritePath=/v1/default(?<segment>/?.*), $\{segment}

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/product/**
          filters:
            - RewritePath=/v1/product(?<segment>/?.*), $\{segment}